services:
  # ----------------------------------------------------------------------------
  # MOTOR RELACIONAL: PostgreSQL (OLTP y posterior Data Warehouse OLAP)
  # ----------------------------------------------------------------------------
  postgres_db:
    image: postgres:17-alpine
    container_name: academico_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      ETL_DB_USER: ${ETL_DB_USER}
      ETL_DB_PASSWORD: ${ETL_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata_academico:/var/lib/postgresql/data
      # Los scripts de database/oltp se ejecutan en orden alfabético durante el
      # primer arranque (01_init... -> 05_usuarios_auth -> 06_bootstrap_rol_app)
      - ./database/oltp:/docker-entrypoint-initdb.d
    networks:
      - red_academica

  # ----------------------------------------------------------------------------
  # MOTOR NOSQL: Neo4j (Malla Curricular y Prerrequisitos)
  # ----------------------------------------------------------------------------
  neo4j_db:
    image: neo4j:5.20-community
    container_name: academico_neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]  # Biblioteca recomendada para algoritmos de grafos
    ports:
      - "7474:7474" # Interfaz Web (Neo4j Browser)
      - "7687:7687" # Protocolo Bolt (Conexión Python)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - red_academica

# ------------------------------------------------------------------------------
# RED Y VOLÚMENES PERSISTENTES
# ------------------------------------------------------------------------------
networks:
  red_academica:
    driver: bridge

volumes:
  pgdata_academico:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local